config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :teams do
    resources :conversations, only: [:index, :new, :create]
    resources :invoices,      only: [:index, :new, :create]
    resources :journals,      only: [:index, :new, :create]
    resources :phone_books,   only: [:index, :new, :create]
    resources :phone_numbers, only: [:index, :new, :create]
    resources :stencils,      only: [:index, :new, :create]
    resources :users,         only: [:index, :new, :create]
  end
  
  resources :conversations,   only: [:show, :edit, :update]
  resources :invoices,        only: [:show, :edit, :update]
  resources :journals,        only: [:show, :edit, :update]
  resources :phone_books,     only: [:show, :edit, :update]
  resources :phone_numbers,   only: [:show, :edit, :update] do
    resources :conversations, only: [:index]
    member do
      post   :purchase
      delete :release
    end
  end
  resources :stencils,        only: [:show, :edit, :update]
  resources :users,           only: [:show, :edit, :update]
  
  resources :memberships,     only: [:create, :update, :destroy]
  resources :phone_book_entries, only: [:create, :update, :destroy]
  
  resources :if_clauses,                only: [:destroy]
  resources :if_starting_clauses,       only: [:create, :update, :destroy]
  resources :if_response_clauses,       only: [:create, :update, :destroy]

  resources :then_clauses,              only: [:destroy]
  resources :then_send_message_clauses, only: [:create, :update, :destroy]
  resources :then_set_status_clauses,   only: [:create, :update, :destroy]
  
  root to: "teams#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :trackable, :lockable, :validatable
  
  has_many :memberships, inverse_of: :user
  has_many :teams, through: :memberships
  has_many :owned_teams, inverse_of: :owner, as: :owner
  
  normalize_attributes :name, :nickname
  
  def team_ids
    memberships.pluck(:team_id)
  end
  
  def membership_for(team_or_id)
    memberships.find_by(team_id: team_or_id.try(:id) || team_or_id) || Membership.new(user: self)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_filter :authenticate_user!

  ##
  # Handle in-bound OmniAuth callbacks
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth( request.env["omniauth.auth"], current_user )

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
	end

  # alias_method :google_oauth2, :all

end

app/controllers/users_controller.rb
class UsersController < ProtectedController
  before_action :set_user, only: [:show, :edit, :update]
  respond_to :html
  
  decorates_assigned :user
  decorates_assigned :users

  # GET /users
  # GET /users.json
  def index
    @users = policy_scope(User)
    respond_with @users
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      authorize @user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      accessible = %w( email name nickname )
      accessible += %w( password password_confirmation ) if params[:user].present? && params[:user][:password].present?
      params.require(:user).permit(*accessible)
    end
end

app/views/users/_form.html.haml
= form_for @user do |f|
  = render partial: 'form_errors', object: @user.errors

  .row
    .col-sm-6
      .well.well-sm
        %fieldset
          %legend= iconify('Details', :edit)
          .form-group
            = f.label :name
            = f.text_field :name, class: 'form-control'
        
          .form-group
            = f.label :nickname
            = f.text_field :nickname, class: 'form-control'

    .col-sm-6
      .well.well-sm
        %fieldset
          %legend= iconify('Password', :key)
          .form-group
            = f.label :password
            = f.password_field :password, class: 'form-control'
        
          .form-group
            = f.label :password_confirmation
            = f.password_field :password_confirmation, class: 'form-control'

  .row
    .col-sm-12
      .form-group
        = f.submit 'Save Changes', class: 'btn btn-primary'
        = link_to 'Discard changes', @user, class: 'btn btn-default'
        

app/views/users/_header.html.haml
- cache @user do
  .container
    .page-header
      %h1
        - if user
          = user.display_name
          %small user
        - else
          Users

app/views/users/_membership.html.haml
- cache [membership, policy(membership).edit?, policy(membership).destroy?] do
  %tr
    %td= membership.team.link_to
    %td
      = membership.team.owner.gravatar_image_tag(20, class: 'img-circle')
      = membership.team.owner.link_to
    %td.text-center= membership.owner_checkmark?
    %td.text-center= membership.administrator_checkmark?
    %td.text-center= membership.developer_checkmark?
    %td.text-center= membership.billing_liaison_checkmark?
    %td.text-center= membership.conversation_manager_checkmark?
    %td.tools
      - if policy(membership).edit?
        %a{ href: '#', 'data-toggle' => "modal", 'data-target' => "#edit_membership_#{ membership.id }", class: 'btn btn-xs btn-default' }= icon(:edit)
        = render partial: 'memberships/edit_modal', object: membership, as: :membership

      - if policy(membership).destroy?
        %a{ href: '#', 'data-toggle' => "modal", 'data-target' => "#destroy_membership_#{ membership.id }", class: 'btn btn-xs btn-default' }= icon(:delete)
        = render partial: 'memberships/destroy_modal', object: membership, as: :membership

app/views/users/_memberships.html.haml
- cache memberships.map{ |o| o.id } do
  %table.table
    %thead
      %tr
        %th Name
        %th Owner
        %th.text-center Owner?
        %th.text-center Administrator?
        %th.text-center Developer?
        %th.text-center Billing<br />Liaison?
        %th.text-center Conversation<br />Manager?
        %th
    %tbody
      = render(partial: 'membership', collection: memberships) || render('memberships_empty')

app/views/users/_memberships_empty.html.haml
%tr
  %td.text-center.text-muted{colspan: 8} No members found

app/views/users/_toolbar.html.haml
- cache do
  .container.toolbar
    / General
    .btn-group.btn-group-sm
      = link_to iconify('Teams', :teams), teams_path, class: 'btn btn-default'
      
      - if @user && !@user.new_record?
        - cache [@user, policy(@user).show?] do
          = link_to iconify('Profile', :user), @user, class: 'btn btn-default'

      - if @user && !@user.new_record? && policy(@user).edit?
        - cache [@user, policy(@user).edit?] do
          = link_to iconify('Edit', :edit), [:edit, @user], class: 'btn btn-default'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', :back

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Name
      %th Nickname
      %th Email
      %th
      %th
      %th
      
  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.nickname
        %td= user.email
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/users/show.html.haml
= user.gravatar_image_tag(120, class: 'gravatar pull-right')
%dl
  %dt Name
  %dd= user.name

  %dt Nickname
  %dd= user.nickname

%h2 Teams
= render partial: 'memberships', object: MembershipDecorator.decorate_collection(policy_scope(@user.memberships))