config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :teams do
    resources :conversations, only: [:index, :new, :create]
    resources :invoices,      only: [:index, :new, :create]
    resources :journals,      only: [:index, :new, :create]
    resources :phone_books,   only: [:index, :new, :create]
    resources :phone_numbers, only: [:index, :new, :create]
    resources :stencils,      only: [:index, :new, :create]
    resources :users,         only: [:index, :new, :create]
  end
  
  resources :conversations,   only: [:show, :edit, :update]
  resources :invoices,        only: [:show, :edit, :update]
  resources :journals,        only: [:show, :edit, :update]
  resources :phone_books,     only: [:show, :edit, :update]
  resources :phone_numbers,   only: [:show, :edit, :update] do
    resources :conversations, only: [:index]
    member do
      post   :purchase
      delete :release
    end
  end
  resources :stencils,        only: [:show, :edit, :update]
  resources :users,           only: [:show, :edit, :update]
  
  resources :memberships,     only: [:create, :update, :destroy]
  resources :phone_book_entries, only: [:create, :update, :destroy]
  
  resources :if_clauses,                only: [:destroy]
  resources :if_starting_clauses,       only: [:create, :update, :destroy]
  resources :if_response_clauses,       only: [:create, :update, :destroy]

  resources :then_clauses,              only: [:destroy]
  resources :then_send_message_clauses, only: [:create, :update, :destroy]
  resources :then_set_status_clauses,   only: [:create, :update, :destroy]
  
  root to: "teams#index"

end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  belongs_to :team, inverse_of: :phone_numbers
  has_many :phone_book_entries, inverse_of: :phone_number
  has_many :phone_books, through: :phone_book_entries
  
  normalize_attributes :provider_sid, :description
  normalize_attribute :number, with: :phone_number
  
  include Workflow
  workflow do
    state :draft do
      event :purchase, transitions_to: :active
    end
    state :active do
      event :release, transitions_to: :inactive
    end
    state :inactive do
      event :purchase, transitions_to: :active
    end
  end
  
  protected
  
  def purchase
  end
  
  def release
  end

end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ProtectedController
  before_action :set_team,         only: [:index, :new]
  before_action :set_phone_number, only: [:show, :edit, :update, :destroy]

  respond_to :html
  
  decorates_assigned :phone_numbers, :phone_number

  def index
    @phone_numbers = policy_scope(@team.phone_numbers).order(:number)
    respond_with(@phone_numbers)
  end

  def show
    respond_with(@phone_number)
  end

  def edit
    respond_with(@phone_number)
  end

  def update
    flash[:success] = 'Hooray!' if @phone_number.update(phone_number_params)
    respond_with(@phone_number)
  end
  
  def purchase
  end
  
  def release
  end

  private
    def set_phone_number
      @phone_number = PhoneNumber.find(params[:id])
      authorize @phone_number

      @team         = @phone_number.team
      authorize @team, :show?
    end

    def phone_number_params
      params.require(:phone_number).permit(:team_id, :workflow_state, :name, :description)
    end
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/phone_numbers/_form.html.haml
= form_for @phone_number do |f|
  = render partial: 'form_errors', object: @phone_number.errors

  .form-group
    = f.label :description, class: 'control-label'
    = f.text_area :description, class: 'form-control'

  .form-group
    = f.submit 'Save changes', class: 'btn btn-primary'
    = link_to 'Discard changes', @phone_number, class: 'btn btn-default'
    

app/views/phone_numbers/_header.html.haml
- cache @phone_number do
  .container
    .page-header
      %h1
        = icon(:phone_numbers)
        - if phone_number
          = phone_number.display_name || 'New'
          %small phone number
        - else
          Phone numbers

app/views/phone_numbers/_phone_number.html.haml
- cache phone_number do
  %tr
    %td= phone_number.link_to
    %td= phone_number.workflow_state_with_icon
      
    %td
      = phone_number.country_flag
      = phone_number.country_name

    %td= link_to iconify(phone_number.phone_books.count, :phone_books),   [phone_number]
    %td= link_to iconify('X', :conversations), [phone_number, :conversations]
    
    %td
      - cache [phone_number, policy(phone_number).show?, policy(phone_number).edit?, policy(phone_number).purchase?, policy(phone_number).release?] do
        = phone_number.show_button
        = phone_number.edit_button
        = phone_number.buy_button
        = phone_number.release_button

app/views/phone_numbers/_phone_numbers.html.haml
%table.table
  %thead
    %tr
      %th Number
      %th Status
      %th Country

      %th= icon(:phone_books)
      %th= icon(:conversations)

      %th
  %tbody
    = render(partial: 'phone_number', collection: phone_numbers) || render('phone_numbers_empty')

app/views/phone_numbers/_phone_numbers_empty.html.haml
%tr
  %td.text-center.text-muted{colspan: 6} No phone numbers are assigned to this team

app/views/phone_numbers/_toolbar.html.haml
- policy = policy(@phone_number || @team.phone_numbers.build)
- cache policy do
  .container.toolbar
    / General
    .btn-group.btn-group-sm
      = link_to iconify('All', :list), [@team, :phone_numbers], class: 'btn btn-default'
      
      - if policy(PhoneNumber.new(team: @team)).purchase?
        = link_to iconify('New', :new), new_team_phone_number_path(@team), class: 'btn btn-default'
  
      - if @phone_number && !@phone_number.new_record?
        - if policy.show?
          = link_to iconify('Details', :phone_number), @phone_number, class: 'btn btn-default'

        - if policy.edit?
          = link_to iconify('Edit', :edit), [:edit, @phone_number], class: 'btn btn-default'

    - if @phone_number && !@phone_number.new_record?
      - if policy.edit?
        / General
        .btn-group.btn-group-sm
          = phone_number.add_phone_book_entry_button( iconify('Add Phone Book', :phone_book) )

        = phone_number.add_phone_book_entry_modal

app/views/phone_numbers/index.html.haml
= render partial: 'phone_numbers', object: phone_numbers

app/views/phone_numbers/new.html.haml
%h1 New phone_number

= render 'form'

= link_to 'Back', phone_numbers_path

app/views/phone_numbers/show.html.haml
.row
  .col-sm-5
    %h2 #{ icon(:details) } Details
    %dl
      %dt Status
      %dd= phone_number.workflow_state_with_icon

      %dt Country
      %dd
        = phone_number.country_flag
        = phone_number.country_name

  .col-sm-7
    %h2 #{ icon(:info) } Description
    = phone_number.description

%h2 Phone Books
= render partial: 'phone_book_entries/phone_book_entries', object: phone_number.phone_book_entries