config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :teams do
    resources :conversations, only: [:index, :new, :create]
    resources :invoices,      only: [:index, :new, :create]
    resources :journals,      only: [:index, :new, :create]
    resources :phone_books,   only: [:index, :new, :create]
    resources :phone_numbers, only: [:index, :new, :create]
    resources :stencils,      only: [:index, :new, :create]
    resources :users,         only: [:index, :new, :create]
  end
  
  resources :conversations,   only: [:show, :edit, :update]
  resources :invoices,        only: [:show, :edit, :update]
  resources :journals,        only: [:show, :edit, :update]
  resources :phone_books,     only: [:show, :edit, :update]
  resources :phone_numbers,   only: [:show, :edit, :update] do
    resources :conversations, only: [:index]
    member do
      post   :purchase
      delete :release
    end
  end
  resources :stencils,        only: [:show, :edit, :update]
  resources :users,           only: [:show, :edit, :update]
  
  resources :memberships,     only: [:create, :update, :destroy]
  resources :phone_book_entries, only: [:create, :update, :destroy]
  
  resources :if_clauses,                only: [:destroy]
  resources :if_starting_clauses,       only: [:create, :update, :destroy]
  resources :if_response_clauses,       only: [:create, :update, :destroy]

  resources :then_clauses,              only: [:destroy]
  resources :then_send_message_clauses, only: [:create, :update, :destroy]
  resources :then_set_status_clauses,   only: [:create, :update, :destroy]
  
  root to: "teams#index"

end

app/models/stencil.rb
class Stencil < ActiveRecord::Base
  belongs_to :team,       inverse_of: :stencils
  belongs_to :phone_book, inverse_of: :stencils
  has_many :if_clauses,   inverse_of: :parent, as: :parent, autosave: true, dependent: :destroy

  normalize_attributes :name, :description
  
  validates_presence_of :name

  accepts_nested_attributes_for :if_clauses

  include Workflow
  workflow do
    state :active do
      event :deactivate, transitions_to: :inactive
    end
    state :inactive do
      event :activate, transitions_to: :active
    end
  end

end

app/controllers/stencils_controller.rb
class StencilsController < ProtectedController
  before_action :set_team,    only: [:index, :new, :create]
  before_action :set_stencil, only: [:show, :edit, :update]

  respond_to :html

  decorates_assigned :stencils, :stencil

  def index
    @stencils = policy_scope(@team.stencils)
    respond_with(@stencils)
  end

  def show
    respond_with(@stencil)
  end

  def new
    @stencil = @team.stencils.build
    respond_with(@stencil)
  end

  def edit
  end

  def create
    @stencil = @team.stencils.build(stencil_params)
    authorize @stencil

    @stencil.save
    respond_with(@stencil)
  end

  def update
    @stencil.update(stencil_params)
    respond_with(@stencil)
  end

  def destroy
    @stencil.destroy
    respond_with(@stencil)
  end

  private
    def set_stencil
      @stencil = Stencil.find(params[:id])
      authorize @stencil
      
      @team = @stencil.team
      authorize @team, :show?
    end
    
    def if_clause_subparams
      [ :type, { then_clauses_attributes: then_clause_subparams } ]
    end
    
    def then_clause_subparams
      [ :type, :message ]
    end

    def stencil_params
      if_clause_params = []
      then_clause_params = [:message]
      params.require(:stencil).permit(:team_id, :workflow_state, :name, :description, :phone_book_id, if_clauses_attributes: if_clause_subparams)
    end
end

app/helpers/stencils_helper.rb
module StencilsHelper
end

app/views/stencils/_form.html.haml
= form_for @stencil do |f|
  = render partial: 'form_errors', object: @stencil.errors
  = f.hidden_field :team_id

  .row
    .col-sm-6
      .well.well-sm
        %fieldset
          %legend
            = icon(:details)
            Details
      
          .form-group
            = f.label :name, class: 'control-label'
            = f.text_field :name, class: 'form-control'
        
          .form-group
            = f.label :description, class: 'control-label'
            = f.text_area :description, class: 'form-control'
        
          .form-group
            = f.label :phone_book_id, class: 'control-label'
            = f.collection_select :phone_book_id, policy_scope(@team.phone_books).decorate, :id, :name, {}, { class: 'form-control' }

  .form-group
    = f.submit 'Save changes', class: 'btn btn-primary'
    = link_to 'Discard changes', @stencil.new_record? ? [@stencil.team, :stencils] : @stencil, class: 'btn btn-default'

app/views/stencils/_header.html.haml
- cache @stencil do
  .container
    .page-header
      %h1
        - if stencil
          = icon(:stencil)
          = stencil.name
          %small stencil
        - else
          = icon(:stencils)
          Stencils

app/views/stencils/_stencil.html.haml
%tr
  %td= stencil.name_with_link
  %td= stencil.workflow_state_with_icon
  %td= stencil.description
  %td= stencil.phone_book.link_to
  %td
    = stencil.small_show_button
    = stencil.small_edit_button

app/views/stencils/_stencils.html.haml
%table.table
  %thead
    %tr
      %th Name
      %th Status
      %th Description
      %th Phone book
      %th
      
  %tbody
    = render(partial: 'stencils/stencil', collection: stencils) || render('stencils/stencils_empty')

app/views/stencils/_toolbar.html.haml
- policy = policy(@stencil || @team.stencils.build)
- cache policy do
  .container.toolbar
    / General
    .btn-group.btn-group-sm
      = link_to iconify('All', :list), [@team, :stencils], class: 'btn btn-default'
      
      - if policy.new?
        = link_to iconify('New', :new), new_team_stencil_path(@team), class: 'btn btn-default'

      - if @stencil && !@stencil.new_record?
        = stencil.toolbar_show_button
        = stencil.toolbar_edit_button
        
      -#
        - if policy.show?
          = link_to iconify('Details', :phone_book), @stencil, class: 'btn btn-default'

        - if policy.edit?
          = link_to iconify('Edit', :edit), [:edit, @stencil], class: 'btn btn-default'

app/views/stencils/edit.html.haml
= render 'form'

app/views/stencils/index.html.haml
= render partial: 'stencils', object: stencils

app/views/stencils/new.html.haml
= render 'form'

app/views/stencils/show.html.haml
.row
  .col-sm-5
    %h2 #{ icon(:details) } Details
    %dl
      %dt Name
      %dd= stencil.name
    %dl
      %dt Status
      %dd= stencil.workflow_state_with_icon
    %h2 #{ icon(:info) } Description
    = stencil.description

  .col-sm-7
    %h2 Actions
    - %w( IfStartingClause IfResponseClause ).each do |if_clause_class|
      - if_clause_class = IfClauseDecorator.decorate( if_clause_class.constantize.new(parent: stencil.model) )
      = if_clause_class.new_with_modal(iconify(if_clause_class.name, :new))
      = if_clause_class.edit_modal

    = render(partial: 'if_clauses/if_clauses', object: stencil.if_clauses)